# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/omkar-ramtekkar/Private-Cocoapods.git'

target 'TestFrameworkApp' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestFrameworkApp

    

end
